# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # .github/workflows/*.yml
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/" # ./
    schedule:
      interval: "weekly"
