[package]
name = "rectgrid-example"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "Apache-2.0"

[lib]
name = "app"
crate-type = ["cdylib", "rlib"]

[dependencies]
rectgrid = { path = "..", features = ["geometry"] }
arbitrary-int = "2"
wasm-bindgen         = { version = "0.2", default-features = false }
wasm-bindgen-futures = { version = "0.4", default-features = false }
libm = { version = "0.2", default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
talc         = { version = "5.1", default-features = false }
spinning_top = { version = "0.3", default-features = false }

[features]
default = []
worker  = []

[profile.release]
panic         = "abort"
lto           = "fat"
strip         = true
opt-level     = "z"
codegen-units = 1
