name: "Deploy to GitHub Pages"

on:
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: "git checkout"
              uses: actions/checkout@v7

            - name: "add wasm32 target"
              run: rustup target add wasm32-unknown-unknown

            - name: "install wasm-pack"
              run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

            - name: "cargo test"
              run: cargo test
              
            - name: "wasm-pack build"
              working-directory: "./examples"
              run: wasm-pack build --target web --out-dir app --out-name app
              
            - name: "setup Github Pages"
              uses: actions/configure-pages@v6
              
            - name: "upload artifact as Github Pages"
              uses: actions/upload-pages-artifact@v5
              with:
                path: "./examples"
                
            - name: "deploy to GitHub Pages"
              id: "deployment"
              uses: actions/deploy-pages@v5
